version: 2

sources:
  - name: iata
    database: nborneo_dev
    schema: analytics
    loader: databricks
    freshness:
      warn_after:
        count: 1
        period: day
      error_after:
        count: 7
        period: day
    loaded_at_field: audit_tgt_load_timestamp

    tables:
      - name: airline_codes
        identifier: brz_airline_codes
      - name: airline_trips
        identifier: brz_airline_trips
      - name: airport_codes
        identifier: brz_airport_codes
